### ISSUE TITLE
Error on step 20 part d

### ISSUE THREAD

**Issue by dnicholes** [gewuek/vitis_ai_custom_platform_flow#1]
I ran into an error when I do the make on Step 20, part D. The error says:

Vitis-AI-Library]$ make
[  0%] Running C++ protocol buffer compiler on proto dpu_model_param
vitis/ai/proto/dpu_model_param.proto:294:3: Expected "required", "optional", or "repeated".
vitis/ai/proto/dpu_model_param.proto:294:25: Missing field number.
make[2]: *** [model_config/vitis/ai/proto/dpu_model_param.pb.cc] Error 1
make[1]: *** [model_config/CMakeFiles/model_config.dir/all] Error 2
make: *** [all] Error 2

Suggestions?

**Comment by gewuek** [comment]
Hi @dnicholes ,

Sorry for the delay. I am not quite familar with the Github system. Especially the issue system.
As I know the "Step 20, part D" is:
```
mkdir build_for_petalinux
cd build_for_petalinux
unset LD_LIBRARY_PATH; source <full_pathname_to_zcu102_dpu_pkg>/pfm/environment-setup-aarch64-xilinx-linux
cmake -DCPACK_GENERATOR=TGZ -DBUILD_SHARED_LIBS=on -DCMAKE_INSTALL_PREFIX=<full_pathname_to_zcu102_dpu_pkg>/pfm/sysroots/aarch64-xilinx-linux/usr ..
make && make install
make package
```
Here we just use the PetaLinux SDK to cross compile the glog.
I would suggest you to double check if you are using PetaLiunx 2019.2, if the PetaLinux SDK is well compiled and installed. And also if the enviroments are set to <full_pathname_to_zcu102_dpu_pkg>.
If it is still can't work, please create a new post on to the forum:
https://forums.xilinx.com/t5/AI-and-Vitis-AI/bd-p/AI
Some of the guys watch that forum has already tested the tutorial.
If they can't answer your question I would look into it after I came back to office(Next Thrusday).

**Comment by gewuek** [comment]
Hi @dnicholes,

Since I haven't got any further questions on that. I am going to close this issue now.
It is still recomended to post your question to https://forums.xilinx.com/t5/AI-and-Vitis-AI/bd-p/AI if you have any further questions. Thanks!
